[versions]
minecraft = "1.20.6"
yarn_mappings = "1.20.6+build.1"
fabric_loader = "0.15.11"
loom = "1.6-SNAPSHOT"
vineflower = "1.10.1"
mixin_squared = "0.1.2-beta.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
mixin_squared = { module = "com.github.bawnorton.mixinsquared:mixinsquared-fabric", version.ref = "mixin_squared" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
